### ISSUE TITLE
system calls error when building for iOS

### ISSUE THREAD

**Issue by hamchapman** [DanBloomberg/leptonica#349]
I'm getting the following errors when building leptonica for iOS:

```
../../../src/gplot.c:402:18: warning: 'system' is deprecated: first deprecated in iOS 8.0 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
        ignore = system(buf);  /* gnuplot || wgnuplot */
                 ^
/Applications/Xcode833.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/stdlib.h:187:6: note: 'system' has been explicitly marked deprecated here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
```

and 

```
../../../src/writefile.c:1028:14: warning: 'system' is deprecated: first deprecated in iOS 8.0 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
    ignore = system(buffer);
             ^
/Applications/Xcode833.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/usr/include/stdlib.h:187:6: note: 'system' has been explicitly marked deprecated here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
```

I see that in 1.76.0 there was a change in relation to `system` calls: https://github.com/DanBloomberg/leptonica/blob/master/src/gplot.c#L395-L397

Is it possible that leptonica could use the suggested `posix_spawn` APIs instead of `system` when building for iOS?

I'll admit that I'm not really sure what the implications would be or what the feasibility of that is, but I'm just following the error messages.

For now I'm able to get it to build by using an older version of the iOS SDK where `system` calls trigger a deprecation warning instead of an error.

For extra context I'm trying to build leptonica as part of this library dependencies: https://github.com/gali8/Tesseract-OCR-iOS

Specifically here's the `Makefile`: https://github.com/gali8/Tesseract-OCR-iOS/blob/master/TesseractOCR/Makefile

**Comment by DanBloomberg** [comment]
Did you get the error when using 1.76.0?   That was released May 2.

Some changes for wrapping "system' were added a few days later.  This introduced a compilation failure on ios , which was fixed on May 10.  The current master should be fine.

**Comment by hamchapman** [comment]
I've just tried with master (specifically [c052295](https://github.com/DanBloomberg/leptonica/commit/c052295)) and I'm still getting at least one error when building with a recent iOS SDK:

```
../../../src/utils2.c:2439:11: error: 'system' is unavailable: not available on iOS
    (void)system(cmd);
          ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk/usr/include/stdlib.h:195:6: note: 'system' has been explicitly marked unavailable here
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
```

**Comment by hamchapman** [comment]
@DanBloomberg would you accept a PR that changes the `OS_IOS` checking to use something as I described with the code above?

**Comment by DanBloomberg** [comment]
Thank you for your careful evaluation of the issue and your well-formatted code.  It does appear that this is a significant problem that needs to be fixed, although you are the first to report it.

I am also concerned that, as you say, system won't be called on macOS.  This can be fixed by changing the code to first check:

  if (LeptDebugOK ...) {
  ...
   }

and then under #ifdef __APPLE__, reverse the order

  #if !TARGET_OS_PHONE && !OS_IOS    (the latter for good measure?)
      (void)system(cmd)
  # else
      L_ERROR(...)

Let me try this and let some android system developers patch it in for an evaluation.
I'll try to get back to you on this in a day.

**Comment by DanBloomberg** [comment]
I made a change to the system wrapper, mostly as you'd suggested, and it tested oK with iOS emulators.

Here's the commit description:

  Apparently, OS_IOS doesn't always guard properly for IOS.
  Hamilton Chapman ran into this problem and suggested a work-around
  using different guards.  With a small modification, this commit implements
  his suggested fix.  It should call 'system' on macOS but not on iOS.

Just pushed to head.
See if this fixes your problem.

**Comment by DanBloomberg** [comment]
@hamchapman 
can we close this?

**Comment by hamchapman** [comment]
I’m afraid I’ve not had a chance to test it yet, but I looked over the changes and they look good. I’m happy for this to be closed and when I get a chance to test it I’ll open a new issue if there’s a problem (which I very much doubt there will be!).

Thanks!

**Comment by DanBloomberg** [comment]
OK, closing for now.

**Comment by lqhart** [comment]
How to build the latest version for iOS?  is there anyone continue this work?
