### ISSUE TITLE
leptonica can't read 16 bps rgb pnm/pam files; sends junk image to tesseract

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#412]
This was reported to tesseract-ocr@googlegroups by infinitepanther@gmail.

Environment
Tesseract 4.0.0-beta.3-249-g607e
leptonica-1.76.0
Linux (hostname removed) 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Current Behavior:
I work at a SaaS firm which provides cloud storage services specializing in documents. As a part of our service, we try to create PDFs with searchable text layers from scanned documents. When processing PPMs which are created by ImageMagick from the original document, Leptonica mangles the image before it can be OCR'd properly by Tesseract. This results in a PDF unreadable by both human eyes and Tesseract. This only seems to happen for some specific documents.

How do I know it's Leptonica, specifically?
I have executed Tesseract with the config values tessedit_write_images 1 and tessedit_pageseg_mode 0. From my understanding, the second option does not enable OCR at all while processing with Tesseract (which speeds up my test cases) and the first option outputs a .tif debug image which is apparently what Leptonica feeds to Tesseract after processing. That image is also mangled.

Sample data
I have extracted a single page from a PDF -- the process works on a page-by-page basis and most of the documents we work with contain highly sensitive information, so I had no other option but to do this. Regardless, it is good sample data. The "pg_0009.ppm" file is the original input fed into Tesseract on the command line which was converted from the original scanned document by ImageMagick. The "tessinput.tif" file is the image produced by the tessedit_write_images 1 option which is supposed to be OCR'd by Tesseract. This particular page caused a seg fault in Tesseract, something that doesn't usually happen, and I suspect it is because the text is overlapped so many times that the OCR engine has too much to handle.

Google Drive since it's too large for an attachment: https://drive.google.com/file/d/1UCzXYu7iusep-bOD6EcKyBs2qXCqVdu5/view?usp=sharing

Expected Behavior:
Leptonica leaves the image mostly intact so that Tesseract can provide a proper text layer for the output PDF. Alternatively, a configuration option is available to bypass Leptonica.

Any and all help is appreciated with this issue. Thanks for reading.

**Comment by DanBloomberg** [comment]
Thank you for this report.  It appears that since the corrupted image crashed tesseract, we have successfully *fuzzed* tesseract.

The problem with your pnm file is that leptonica did not have any code to read 16 bps rgb files (pnm type 6).  When I wrote that code, 16 bps was not part of the standard.

This has now been implemented, and you can get the working pnmio.c file from the head of the leptonica github master.

To fix the problem, I had to take the LSB of each 16 bit sample.  This was a surprise, because according to the wikipedia synopsis of pnm:

_The original definition of the PGM and the PPM binary formats (the P5 and
P6 formats) did not allow bit depths greater than 8 bits. One can of course
use the ASCII format, but this format both slows down reading and makes the
files much larger. Accordingly, many programmers extended the format to
allow higher bit depths. Using higher bit depths encounters the problem of
having to decide on the endianness
<https://en.wikipedia.org/wiki/Endianness> of the file. The various
implementations could not agree on which byte order to use, and some
connected the 16-bit endianness to the pixel packing order.[8]
<https://en.wikipedia.org/wiki/Netpbm_format#cite_note-8> In Netpbm
<https://en.wikipedia.org/wiki/Netpbm>, the *de facto
<https://en.wikipedia.org/wiki/De_facto>* standard implementation of the
PNM formats, the most significant byte is first.[9]
<https://en.wikipedia.org/wiki/Netpbm_format#cite_note-9>_

I have a question for you.  Why are you making 16 bps (48 bpp) pnm files? These are 50 MB each.  You don't need anything near 16 bits/sample.  For text, 4 bps (16 levels) is already overkill.

  -- Dan

**Comment by 36PopTarts** [comment]
Your question is well-warranted and not one that I can answer. I've had all of about a week to look at this code and I did not originally write it.

**Comment by zdenop** [comment]
@DanBloomberg : not sure if this is related to this issue, but I tried to load this
[ppm file](https://github.com/DanBloomberg/leptonica/files/3024251/numpad.ppm.zip) (zipped to for upload to github) and save it as png with leptonica, but I got empty/transparent file:

```
#include <leptonica/allheaders.h>

int main() {

char *fileout = "test.png";
char *filein = "numpad.ppm";

    PIX * pixs = pixRead(filein);
    if (!pixs) {
      fprintf(stderr, "Leptonica can't process input file: %s\n", filein);
      return 2;
    }
    fprintf(stdout, "Loaded...\n");
    int retv = pixWrite(fileout, pixs, IFF_PNG);
    fprintf(stdout, "Return value: %d.\n", retv);
    pixDestroy(&pixs);
    return retv;
}
```

**Comment by DanBloomberg** [comment]
@zdenop 
Yes, that is what I was getting as well.  The problem is now fixed at head.

**Comment by zdenop** [comment]
@DanBloomberg : unfortunatelly I still get just transparent/empty result.

**Comment by DanBloomberg** [comment]
@zdenop 
I can assure you that it works properly on the 16 bps pg_0009.ppm image supplied with this issue.

**Comment by zdenop** [comment]
Yes, pg_0009.ppm works now, but can you please try [ppm file](https://github.com/DanBloomberg/leptonica/files/3024251/numpad.ppm.zip) from [my comment about](https://github.com/DanBloomberg/leptonica/issues/412#issuecomment-478131338)?
I am sorry for not being clear.

**Comment by DanBloomberg** [comment]
No, you were perfectly clear -- I was being sloppy.  Will look at your file
tomorrow.

**Comment by DanBloomberg** [comment]
@zdenop 
The problem was a ridiculous bug that has been in the code for a long time.  Thank you for checking and persisting.  Now (really) fixed at head.

**Comment by zdenop** [comment]
Thanks! It works now.
