### ISSUE TITLE
fileinfo failed to read tiff for spp = 2

### ISSUE THREAD

**Issue by t246246** [DanBloomberg/leptonica#426]
For example, using imagemagick one can create 8bit gray + alpha tiff
```
% convert -size 10x10 xc:white -alpha set -channel RGBA -fill 'graya(255,0.5)' -opaque 'graya(255,1)' -depth 8 w8.tif
```
and it is viewable with gimp2, krita etc.
```
% tiffinfo w8.tif 
TIFF Directory at offset 0xd0 (208)
  Image Width: 10 Image Length: 10
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 2
  Rows/Strip: 10
  Planar Configuration: single image plane
  Page Number: 0-1
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
```
However fileinfo failed to read it.
```
% fileinfo w8.tif 
===============================================
Reading the header:
  input image format type: tif
  w = 10, h = 10, bps = 8, spp = 2, iscmap = 0
===============================================
Reading the full image:
Error in pixReadFromTiffStream: spp not in set {1,3,4}
Error in pixReadStream: tiff: no pix returned
Error in pixRead: pix not read
Error in writeImageFileInfo: failure to read full image of w8.tif
```

whereas fileinfo can read the file if it is png.
```
% convert -size 10x10 xc:white -alpha set -channel RGBA -fill 'graya(255,0.5)' -opaque 'graya(255,1)' -depth 8 w8.png
```
```
% fileinfo w8.png
Info in readHeaderMemPng: gray + alpha: will extract as RGBA (spp = 4)
===============================================
Reading the header:
  input image format type: png
  w = 10, h = 10, bps = 8, spp = 2, iscmap = 0
  xres = 0, yres = 0
===============================================
Reading the full image:
Info in pixReadStreamPng: converting (gray + alpha) ==> RGBA
  input image format type: png
  w = 10, h = 10, d = 32, spp = 4, wpl = 10
  xres = 0, yres = 0
  text: 2019-04-26T22:45:56+09:00
  colormap does not exist
===============================================
Info in boxaWriteMem: work-around: writing to a temp file
Error in callSystemDebug: iOS 11 does not support system()
```

**Comment by DanBloomberg** [comment]
Thank you for providing such a detailed bug report.  I should be able to fix this in a few days.

  -- Dan

**Comment by DanBloomberg** [comment]
Fixed.  Now does same as with png -- converts gray+alpha to rgba, because leptonica does not internally support gray+alpha ( spp=2, bps=8) images

**Comment by t246246** [comment]
Thank you for your fast fix. It seems you forgot the case bps=16 and spp =2.
```
convert -size 100x100 xc:white -alpha set -channel RGBA -fill 'graya(255,0.5)' -opaque 'graya(255,1)' -depth 16 w16.tif
```
```
$ tiffinfo w16.tif 
TIFF Directory at offset 0x9c48 (40008)
  Image Width: 100 Image Length: 100
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 2
  Rows/Strip: 100
  Planar Configuration: single image plane
  Page Number: 0-1
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
```

Just compiled from mater on macOS.

```
$ /usr/local/bin/fileinfo w16.tif 
===============================================
Reading the header:
  input image format type: tif
  w = 100, h = 100, bps = 16, spp = 2, iscmap = 0
===============================================
Reading the full image:
  input image format type: tif
  w = 100, h = 100, d = 32, spp = 3, wpl = 100
  xres = 0, yres = 0
  colormap does not exist
  Tiff header information:
    One page in file
TIFF Directory at offset 0x9c48 (40008)
  Image Width: 100 Image Length: 100
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Extra Samples: 1<unassoc-alpha>
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 2
  Rows/Strip: 20
  Planar Configuration: single image plane
  Page Number: 0-1
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
===============================================
```
So simple program
```
$ cat test.c
#include "allheaders.h"

int main(int argc, char *argv[]) {
  char *in, *out;
  PIX *pixs = NULL, *pixd = NULL;

  in = argv[1];
  out = argv[2];

  if ((pixs = pixRead(in)) == NULL) 
    exit(1);

  if((pixWrite(out, pixs, IFF_TIFF)) != 0) {
    if (pixd != NULL)
      pixDestroy(&pixs);
    exit(2);
  }

  pixDestroy(&pixs);

  exit(0);
}

% clang -I /usr/local/include/leptonica/ test.c -llept
% ./a.out w16.tif out.tif
```
breaks the file.
```
% tiffinfo out.tif
```
TIFF Directory at offset 0x7538 (30008)
  Image Width: 100 Image Length: 100
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 100
  Planar Configuration: single image plane

% compare w16.tif out.tif -format '%c\n' -metric MSE NULL:
16384.3 (0.250008)
```

**Comment by t246246** [comment]
Also give w8.tif (at my first post) as an input, it segfaults on my macOS mojave 10.14.4. (libtiff comes from macport tiff @4.0.10_1)

**Comment by DanBloomberg** [comment]
You're absolutely right -- I was careless with the input cases.  So that's easy to fix.

I wasn't sure if I should have put that line in (l. 980 that caused the crash), and it now appears that was a mistake.  Can you please remove that line from the source code, recompile and see if it doesn't crash.

**Comment by DanBloomberg** [comment]
It turns out that in spite of the comment in tiffio.c, this tiff reading shim has never handled samples larger than 8 bits except for the case of 16 bit gray.  The shim was never intended to support all possible tiff files, the way, for example, gimp (imagemagick) does, with a relatively elaborate internal image format.

But what the shim should do is clearly state what is and what is not supported, and for those configurations that are supported, it should save the bits properly, so that nothing is lost.  Or, if something is lost, such as stripping 16 -> 8 bit samples in png, it is stated.  And I've implemented that in pngio.c for two reasons: (1) it's good to be able to handle these images at least one place in the library and (2) png makes it easy by providing an internal 'transform' that accomplishes this.

There is yet another 'principle': on a further write/read cycle, you end up with the same raster image. Again, part of the "don't lose information" constraint.

**Comment by DanBloomberg** [comment]
Turned out it was reading 16 bps rgb images just fine, so re-enabling.
Still not planning to handle 16 bps gray+alpha.

**Comment by t246246** [comment]
After removing setting TIFFTAG_EXTRASAMPLES to EXTRASAMPLE_UNASSALPHA line, it stopped crashing.  However the result file is complained by tiffinfo:
```
% tiffinfo out8.tif 
TIFFReadDirectory: Warning, Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples..
TIFF Directory at offset 0x198 (408)
  Image Width: 10 Image Length: 10
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 4
  Rows/Strip: 10
  Planar Configuration: single image plane
```

So it should be set.

I tried to set it later by tiffset:
```
bash-3.2$ /opt/local/bin/tiffset -s 338 1 2 out8.tif 
TIFFReadDirectory: Warning, Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples..
bash-3.2$ /opt/local/bin/tiffinfo out8.tif 
TIFFReadDirectory: Warning, Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples..
TIFF Directory at offset 0x678 (1656)
  Image Width: 10 Image Length: 10
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 5<unassoc-alpha, unspecified, unspecified, unspecified, unspecified>
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 8
  Rows/Strip: 10
  Planar Configuration: single image plane
```

So I think it's a bug of libtiff.

**Comment by t246246** [comment]
After reading your policy,  another considerable file is 16-bit float and 32-bit float.
The latter is properly rejected, but the former is not properly rejected in your current program:

```
$ tiffinfo 16bit-float-RGBA.tif 
TIFF Directory at offset 0x8ec0 (36544)
  Image Width: 256 Image Length: 256
  Resolution: 100, 100
  Bits/Sample: 16
  Sample Format: IEEE floating point
  Compression Scheme: Deflate
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  Samples/Pixel: 4
  Rows/Strip: 8
  Planar Configuration: single image plane
  DocumentName: 16bit-float-RGBA
  ICC Profile: <present>, 880 bytes
  Predictor: none 1 (0x1)

$ tiffinfo 32bit-float-RGBA.tif 
TIFF Directory at offset 0x1106e (69742)
  Image Width: 256 Image Length: 256
  Resolution: 100, 100
  Bits/Sample: 32
  Sample Format: IEEE floating point
  Compression Scheme: Deflate
  Photometric Interpretation: RGB color
  Extra Samples: 1<unassoc-alpha>
  Samples/Pixel: 4
  Rows/Strip: 8
  Planar Configuration: single image plane
  DocumentName: 32bit-float-RGBA
  ICC Profile: <present>, 880 bytes
  Predictor: none 1 (0x1)
```
```
$ /usr/local/bin/fileinfo 16bit-float-RGBA.tif 
===============================================
Reading the header:
  input image format type: tif
  w = 256, h = 256, bps = 16, spp = 4, iscmap = 0
===============================================
Reading the full image:
Error in pixReadFromTiffStream: failed to read tiffdata
Error in pixReadStream: tiff: no pix returned
Error in pixRead: pix not read
Error in writeImageFileInfo: failure to read full image of 16bit-float-RGBA.tif

$ /usr/local/bin/fileinfo 32bit-float-RGBA.tif 
Error in tiffReadHeaderTiff: bps not in set {1,2,4,8,16}
Error in pixReadHeader: tiff: no header info returned
Error in writeImageFileInfo: failure to read header of 32bit-float-RGBA.tif
```

You need to check also sample format tag.

They are easily made by krita. I upload it for your test.
[float.tif.zip](https://github.com/DanBloomberg/leptonica/files/3125982/float.tif.zip)

**Comment by t246246** [comment]
I see the reason of crash. The line should be:
```
uint16    val[1];

        val[0] = EXTRASAMPLE_UNASSALPHA;
	TIFFSetField(tif, TIFFTAG_EXTRASAMPLES, (l_uint16)1, &val);
```

**Comment by t246246** [comment]
> Turned out it was reading 16 bps rgb images just fine, so re-enabling.

But if I understand it right, writing 16 bit rgb is not supported. 
In pixWriteToTiffStream(), TIFFTAG_BITSPERSAMPLE is set to 8 8 8 (or 8 8 8 8 for RGBA).

So currently, 16 bit rgb(a) turned to 8 bit rgb(a) when writing.

Reading 16 bit gray alpha as 8 bit seems to not so difficult,  but when writing 16 bit RGB(A) is implemented someday, it would make trouble.  So I agree with you when you implement reading 16 bit gray alpha (or any other unimplemented format) someday, reader should keep all 16 bit value internally.

**Comment by DanBloomberg** [comment]
Thank you for the hint on using the EXTRASAMPLE declaration.  As it turns out, we need to use the associated alpha (which makes sense).  So that's in, and we no longer get the warning from tiffinfo and display.  I hope we're done with this for now  :-)

**Comment by DanBloomberg** [comment]
Any idea how the tiff reader can tell if the tiff data is an array of floats instead of ints?

**Comment by t246246** [comment]
You can check it by TIFFTAG_SAMPLEFORMAT.
https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html

**Comment by DanBloomberg** [comment]
Thank you.  It's actually a good test to include.
