### ISSUE TITLE
pixFindBaselines() returns |baselines| != |baseline_endpoint_pairs|

### ISSUE THREAD

**Issue by AnonymousCoward128746** [DanBloomberg/leptonica#766]
Leptonica is a wonderfully useful library, thank you so much for all your hard and valuable work.

I am using `pixFindBaselines` and passing in the optional `ppta` arg in order to get the approximate endpoints for each baseline. Recently, I discovered that the number of entries in `ppta` (the endpoints pairs) may be smaller than the number of baselines returned in `na`. This was surprising to me. 

I suspect the culprit code is here:
https://github.com/DanBloomberg/leptonica/blob/d5ea1db60fe0c215fcb8201a1ee1a3fe8986917b/src/baseline.c#L245-L255

This does not guarantee that an item will be added to `pta` for each baseline, and it sometimes fails in practice on real-world images.
 
Best Wishes,

**Comment by DanBloomberg** [comment]
I agree that this could/should be more robust.

Can you post an image you use (with text lines essentially horizontal), that reproduces the problem?

**Comment by AnonymousCoward128746** [comment]
Sorry, I should have attached one to begin with. This is a cleaned redacted image, but it returns the same outputs as the original, namely that three baselines are correctly identified, but the returned endpoints don't show anything for the middle line
[Image link](https://github.com/user-attachments/assets/ad144c31-1de7-4bbd-a144-fd36ff9d03a2)

Here is some JSON test output I hacked into my code. `ys` are the baseline y coordinates, and `endpoints` is a list of tuples `(x0,y0,x1,y1)` for each pair of endpoints returned by the function

```JSON
{
  "ys": [
    1750.0,
    1792.0,
    1831.0
  ],
  "endpoints": [
    [
      124.0,
      1750.0,
      1164.0,
      1750.0
    ],
    [
      124.0,
      1831.0,
      1164.0,
      1831.0
    ]
  ]
}
```

**Comment by DanBloomberg** [comment]
Thanks for finding this problem.
It should now be fixed.
I also added a couple of more tests in baseline_reg.

**Comment by AnonymousCoward128746** [comment]
The changes still keep the conditional that tries (IIUC) to match up the detected endpoints to the detected baseline, and this match up might still fail, so in theory this could still happen for some inputs, right? 

I'll be able to run the new code over my corpus within the next few days and I'll let you know if this fix generalizes properly.

Thank you.

**Comment by DanBloomberg** [comment]
You are correct that it may be still theoretically possible to join the lines after they've initially been located in ```naloc```.
However, I believe this will now be a rare event, because the only morphological operators used to join line segments is strictly horizontal.  It was the small vertical closing at 4x reduction that was responsible for joining those two lines.

**Comment by AnonymousCoward128746** [comment]
I confirm that the issue with the previous test image is fixed.

But, for this [test2.png](https://github.com/user-attachments/assets/0c7e36ff-7669-4060-a416-1f1b2c7504ed) the functions returns more than one endpoint pair for the middle line, and so again the number of endpoint pairs does not match the number of baselines.

**Comment by DanBloomberg** [comment]
That's actually the design, because sometimes you can have a textline with a large gap, such that two separate textblocks are found on it.  That is the case, for example, in the case of the pedante.079.jpg image in baseline_reg.c, where two of the lines of text have separate text blocks.  So a 1:1 correspondence of baseline locations with  text segments is not required.

However, in the situation you indicated with test2.png, a bogus textbox fragment is generated above the third line, which has a base close to the second line.  I've added a filter to remove these small-height boxes, so in your example it is now eliminated and there are only the 3 correct line segments associated with the 3 actual baselines.

A new commit implements this.

**Comment by AnonymousCoward128746** [comment]
Thank you. Understood, that makes sense for multi-column layouts.

Both `test1.png` and `test2.png` pass now.

Here is [test3.png](https://github.com/user-attachments/assets/34ab056c-eb7c-461a-a2a7-0c2ff3a4ad24). The runt last line returns no endpoints from the function.

Friendly side note: git expects a commit message to include a blank line between the "subject" (first) row and the reset of the commit message body. Without it, `git log` output suffers.

**Comment by DanBloomberg** [comment]
Thank you for the git tip!

The morphological opening ```o30.1``` in line 222 is what removes runt lines that are less than 120 pixels long  (we're working at 4x reduction).  I'm OK with this.  Note if you were to change that to ```o20.1```, the endpoints of last line would be returned.

**Comment by AnonymousCoward128746** [comment]
As I wrote earlier, I do think it's reasonable to filter out runts. But, if a baseline is recognized as valid it should have (at least one) pair or endpoints returned. To have a line without endpoints does not make sense to me.

**Comment by DanBloomberg** [comment]
I agree with you.  Code modified appropriately.

**Comment by AnonymousCoward128746** [comment]
I tested on 300+ images and it works much better. Most of the mismatches occurred on dual-column pages as intended, but there were a handful of cases where visually I could see no reason for multiple endpoint segments: [test4.png](https://github.com/user-attachments/assets/fc0c5638-f9d7-4a86-96d4-cbda8c9f2b82).

The baseline elimination branch was taken quite often. I guess you could chalk it up bad typesetting that there are a lot of widows(*) in this document. In pages from text like plays or interviews, where each response is just a sentence or two, it's quite common to get this. On some pages I had as many as 4 widow lines eliminated. I can always tweak the threshold, and for a morphological-only solution, this is a reasonable compromise.

Finally, I use an ugly trick to easily get the vertical extent of a line, which is to combining the baselines returned from running `pixFindBaselines` on the image and it's top-down mirrored version. Surprisingly, mirroring the image vertically often changes the number of detected baselines. What are your thoughts on this?

(*) That's the proper typographic term for a line consisting of a single word at the end of a paragraph, I learned.

**Comment by AnonymousCoward128746** [comment]
Here's a suggestion for a heuristic that might better handle widows:

1. If sufficient lines are found on the page, the median of the y-coord differences between baselines should provide a good estimate on line spacing ("leading"). And you can verify it by ensuring the variance of the samples is small.
2. If a short line to be pruned falls within a  leading+/-delta from a baseline, **and** one of the endpoints matches one of the endpoints from the same neighbor lines, you could use a second, more lenient threshold for pruning false positives.

I think this would cover a high percentage of cases for widows, in most typical page layouts.

Would you be interested in a PR for consideration once we wrap things up here? It shouldn't be that difficult to implement.

**Comment by DanBloomberg** [comment]
Thank you for the investigation.

You make a good suggestion to reduce the number of widows (are 'orphans' just widows on a new page?).

The implementation could be a bit tricky if it were to revise pixFindBaselines(), because the morphological filter with the opening will destroy small widows.  Also, I would not want to change the interface.

Let me think about this.  I might make a second function with at least one extra parameter, that would share much of pixFindBaselines() but would be gentler on the widows.

If you could, please put up a couple of pages with lots of widows for experimentation.

**Comment by AnonymousCoward128746** [comment]
Here's a synthetic page at 10pt, a4paper, 300dpi. Multiple widows are not detected as baselines but apparently not due to the new "short baseline removal" (SBR).     [test5.png](https://github.com/user-attachments/assets/aa42d2b6-5430-4682-9269-f11d89b33f44)
    
And a real-world image in a dialog/interview format which triggers 5 SBRs. I can't swear this or previous test images are really at 300DPI. [test6.png](https://github.com/user-attachments/assets/f1529791-86fa-4fd4-9c35-e89230544b2c)

**Comment by DanBloomberg** [comment]
Those are good test images.  test5 is 300 ppi on A4; test6 is 200 ppi on 11 x 8.5.  You can tell from the height.   At 300 ppi, an 11.69 inch tall page is h = 3508.  At 200 ppi, an 11 inch tall page is 2200.

**Comment by DanBloomberg** [comment]
See Commit 4e64214.
Added test images 5 & 6.
Generalized to add a parameter specifying the min block with retained.
All saved baselines should have at least one text block referenced to them (i.e., sitting on them)

**Comment by AnonymousCoward128746** [comment]
This is another big improvement. I see a lot of split baselines (mutliple endpoint pairs for same y value) but these are mostly limited to page headers being detected as multiple columns (left pagenum, and right caption), which I understand is by design.

[test7.png](https://github.com/user-attachments/assets/e30ac4de-8fb4-4943-8311-7ed4dda94a07) is a real-world example in which two ordinary full-width lines are detected as multiple columns by `pixFindBaselinesGen(minw=1)`.

**Comment by DanBloomberg** [comment]
Thanks!

I can 'fix' this by changing l.304 to read ```bh > 12```.   Both the extra components were 3 pixels high at 4x reduction.

Note that if ```minw < 12```, there is no final horizontal opening in the morphological command on l.269.

One thing that has me puzzled is that before changing bh in l.304, running this test script:
```
    pix0= pixRead("test7.png");
    pix1 = pixConvertTo1(pix0, 128);
    pixWrite("baseline4.png", pix1, IFF_PNG);
    pixa1 = pixaCreate(0);
    na1 = pixFindBaselinesGen(pix1, 1, &pta1, pixa1);
    numaWriteStderr(na1);
    ptaWriteStream(stderr, pta1, 1);
    pix2 = pixaDisplayTiledInColumns(pixa1, 1, 1.0, 30, 3);
    pixWrite("/tmp/junk1.png", pix2, IFF_PNG);
    pixDestroy(&pix0);
    pixDestroy(&pix1);
    pixDestroy(&pix2);
    numaDestroy(&na1);
    pixaDestroy(&pixa1);
    ptaDestroy(&pta1);
```
and getting this output:
```
Numa Version 1
Number of numbers = 2
  [0] = 610.000000
  [1] = 1274.000000


 Pta Version 1
 Number of pts = 8; format = integer
   (620, 610)
   (640, 610)
   (136, 610)
   (624, 610)
   (984, 1274)
   (1084, 1274)
   (132, 1274)
   (1068, 1274)
```
it generates this 

![Image](https://github.com/user-attachments/assets/c09748c1-687a-416a-9d44-e13be25b8327)

 image for junk1.png, and the last page image with the underlines doesn't have the two bogus ones.  Don't know why.

**Comment by AnonymousCoward128746** [comment]
There are obvious limits to what's attainable using a classical morphological approach. It's up to you to say when you think you've reached them. I think you may just have 😃  .  

One can push this further by using more global information, like inter-line mutual alignment and so forth, but users have everything required to implement a custom solution of their own and s o it's reasonable for leptonica to satisfy itself with just basic implementations. Most developers who need better accuracy for computer vision would today reach for AI, anyway.

Do you feel like this is a good place to stop? The fixes to `pixFindBaselines` and the addition of `pixFindBaselinesGen` are already a marked improvement.

**Comment by DanBloomberg** [comment]
Yes, I agree this is a good place to stop.  As you say, morphological filtering methods without using feedback on things like interline distance remain brittle.

Thank you for your interest and help.  I hope you find it useful.

**Comment by AnonymousCoward128746** [comment]
You've been great, I really appreciate all the attention you gave to this. 👍
